image: php:7.4-cli-alpine

cache:
  key: composer
  paths:
    - vendor

before_script:
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  - composer validate
  - composer install

test:
  script:
    - ./vendor/bin/phpunit

