image: "phpdockerio/php74-cli:latest"

before_script:
  - apt-get update && apt-get -y --no-install-recommends install git php-xdebug php7.4-bcmath php7.4-bz2
  - apt-get clean; rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* /usr/share/doc/*

stages:
  - validate
  - install
  - phpcs
  - test

build:
  stage: validate
  script:
    - composer validate

build:
  stage: install
  script:
    - composer install

phpcs:app:
  stage: phpcs
  script:
    - vendor/bin/phpcs --ignore-annotations --standard=PSR12 src tests

test:app:
  stage: test
  script:
    - vendor/bin/phpunit