image: php:latest

cache:
  key: composer
  paths:
    - vendor

before_script:
  - pecl install xdebug
  - docker-php-ext-enable xdebug
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/bin --filename=composer
  - composer install

validate_composer:
  script:
    - composer validate

test:
  script:
    - ./vendor/bin/phpunit

