stages:
  - build
  - validate composer

build:
  stage: build
  script:
    - docker build --rm -t php-skelleton -f docker/phpdocker/php-for-cli/Dockerfile .

build:
  stage: validate composer
  script:
    - docker run --rm --entrypoint /bin/bash php-skelleton -c "cd /application && composer validate"

