name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']
    steps:
      - uses: actions/checkout@v1
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php-versions }}
          extensions: mbstring, gd, zip
          ini-values: max_execution_time=600, memory_limit=-1
          coverage: xdebug
      - name: Install dependencies
        run: |
          curl -sS https://getcomposer.org/installer | php -- --filename=composer
          composer validate
          composer install
      - name: Check code quality
        run: |
          vendor/bin/phpcs --ignore-annotations --standard=PSR12 src tests
      - name: Run tests
        run: |
          vendor/bin/phpunit
      - name: Check coverage
        run: |
          vendor/bin/php-coverage-checker build/clover.xml 100
